server.port=8087
spring.application.name=timeline-backend

spring.data.redis.host=redis
spring.data.redis.port=6379

secret.key=the00best10signing20key30for40rohans50project
post.backend.fetch.postbypostid=http://post-backend:8086/api/v1/post/getPostsByIds
post.backend.fetch.postbyuserid=http://post-backend:8086/api/v1/post/getPostsForUser/{userId}
redis.cache.postids.size=200